apiVersion: v1
kind: Pod
metadata:
   name: msg-api-mp-client
   labels:
      app: msg-api-mp-client
spec:
   containers:
     - name: msg-api-client
       image: kiefinger/msg-api-mp-client:latest
       resources:
         requests:
           memory: "1Mi"
       ports:
         - containerPort: 9081
           protocol: TCP
       env:
#        - name: MSG_API_MP_DEMO_URL
#          value: http://localhost:31929/msg-api-mp-demo/System
         - name: MSG_API_MP_DEMO_URL
           valueFrom:
             configMapKeyRef:
               name: msg-api-mp-client-data
               key: MSG_API_MP_DEMO_URL
 
